/*!
	wow.export (https://github.com/Kruithne/wow.export)
	Authors: Kruithne <kruithne@gmail.com>
	Based off original works by Dmitry Chestnykh <dmitry@codingrobots.com>
	License: MIT
 */
#pragma once

#include <cstdint>
#include <array>
#include <vector>
#include <string_view>
#include <span>

class BufferWrapper;

namespace casc {

/**
 * Salsa20 stream cipher implementation.
 *
 * JS equivalent: class Salsa20 — module.exports = Salsa20
 */
class Salsa20 {
public:
	/**
	 * Construct a new Salsa20 instance.
	 * @param nonce 8 byte nonce.
	 * @param key   16 or 32 byte key as hex string.
	 * @param rounds Defaults to 20.
	 */
	Salsa20(std::span<const uint8_t> nonce, std::string_view key, int rounds = 20);

	/**
	 * Set the key used by this instance.
	 * @param key 16 or 32 bytes.
	 */
	void setKey(std::vector<uint8_t> key);

	/**
	 * Set the nonce used by this instance.
	 * @param nonce 8 bytes.
	 */
	void setNonce(std::span<const uint8_t> nonce);

	/**
	 * Generate a specific amount of bytes.
	 * @param byteCount Number of bytes to generate.
	 * @returns BufferWrapper containing the generated bytes.
	 */
	BufferWrapper getBytes(size_t byteCount);

	/**
	 * Process the given input (XOR with keystream).
	 * @param buf Input buffer.
	 * @returns BufferWrapper containing the processed output.
	 */
	BufferWrapper process(BufferWrapper& buf);

private:
	/**
	 * Reset the internal block counter.
	 */
	void _reset();

	/**
	 * Increment the internal block counter.
	 */
	void _increment();

	/**
	 * Generate a 64-byte block from the key, nonce and counter.
	 */
	void _generateBlock();

	int rounds_;
	std::array<uint32_t, 4> sigma_;
	std::array<uint32_t, 8> keyWords_;
	std::array<uint32_t, 2> nonceWords_;
	std::array<uint32_t, 2> counter_;
	std::array<uint8_t, 64> block_;
	int blockUsed_;
};

} // namespace casc
